name: Deploy

on:
  push:
    branches: [ main , development ]

jobs:
  verify:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java-version: [ 11 ]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - run: mvn verify -B -e

  release:
    needs: verify
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.gpg_private_key }}") | gpg --batch --import
      - name: publish to snapshot
        run: mvn --no-transfer-progress clean deploy -B -e -Dci=true -Dgpg.passphrase=${{ secrets.gpg_passphrase }}
        env:
          SONATYPE_USERNAME: ${{ secrets.nexus_username }}
          SONATYPE_PASSWORD: ${{ secrets.nexus_password }}